/* THIS FILE WAS GENERATED. DO NOT EDIT. */
#ifndef DF_TALK_CHOICE_TYPE_H
#define DF_TALK_CHOICE_TYPE_H
namespace df {
  namespace enums {
    namespace talk_choice_type {
      enum talk_choice_type : int32_t {
        Greet,
        Nevermind,
        Trade,
        AskJoin,
        AskSurroundings,
        SayGoodbye,
        AskStructure,
        AskFamily,
        AskProfession,
        AskPermissionSleep,
        AccuseNightCreature,
        AskTroubles,
        BringUpEvent,
        SpreadRumor,
        ReplyGreeting,
        RefuseConversation,
        ReplyImpersonate,
        BringUpIncident,
        TellNothingChanged,
        Goodbye2,
        ReturnTopic,
        ChangeSubject,
        AskTargetAction,
        RequestSuggestAction,
        AskJoinInsurrection,
        AskJoinRescue,
        StateOpinion,
        anon_1,
        anon_2,
        AllowPermissionSleep,
        DenyPermissionSleep,
        anon_3,
        AskJoinAdventure,
        AskGuideLocation,
        RespondJoin,
        RespondJoin2,
        OfferCondolences,
        StateNotAcquainted,
        SuggestTravel,
        SuggestTalk,
        RequestSelfRescue,
        AskWhatHappened,
        AskBeRescued,
        SayNotRemember,
        anon_4,
        SayNoFamily,
        StateUnitLocation,
        ReferToElder,
        AskComeCloser,
        DoBusiness,
        AskComeStoreLater,
        AskComeMarketLater,
        TellTryShopkeeper,
        DescribeSurroundings,
        AskWaitUntilHome,
        DescribeFamily,
        StateAge,
        DescribeProfession,
        AnnounceNightCreature,
        StateIncredulity,
        BypassGreeting,
        AskCeaseHostilities,
        DemandYield,
        HawkWares,
        YieldTerror,
        Yield,
        ExpressOverwhelmingEmotion,
        ExpressGreatEmotion,
        ExpressEmotion,
        ExpressMinorEmotion,
        ExpressLackEmotion,
        OutburstFleeConflict,
        StateFleeConflict,
        MentionJourney,
        SummarizeTroubles,
        AskAboutIncident,
        AskDirectionsPerson,
        AskDirectionsPlace,
        AskWhereabouts,
        RequestGuide,
        RequestGuide2,
        ProvideDirections,
        ProvideWhereabouts,
        TellTargetSelf,
        TellTargetDead,
        RecommendGuide,
        ProfessIgnorance,
        TellAboutPlace,
        AskFavorMenu,
        AskWait,
        AskFollow,
        ApologizeBusy,
        ComplyOrder,
        AgreeFollow,
        ExchangeItems,
        AskComeCloser2,
        InitiateBarter,
        AgreeCeaseHostile,
        RefuseCeaseHostile,
        RefuseCeaseHostile2,
        RefuseYield,
        RefuseYield2,
        Brag,
        DescribeRelation,
        anon_5,
        AnnounceLairHunt,
        RequestDuty,
        AskJoinService,
        AcceptService,
        TellRemainVigilant,
        GiveServiceOrder,
        WelcomeSelfHome,
        anon_6,
        AskTravelReason,
        TellTravelReason,
        AskLocalRuler,
        ComplainAgreement,
        CancelAgreement,
        SummarizeConflict,
        SummarizeViews,
        AskClaimStrength,
        AskArmyPosition,
        AskOtherClaims,
        AskDeserters,
        AskSiteNeighbors,
        DescribeSiteNeighbors,
        RaiseAlarm,
        DemandDropWeapon,
        AgreeComplyDemand,
        RefuseComplyDemand,
        AskLocationObject,
        DemandTribute,
        AgreeGiveTribute,
        RefuseGiveTribute,
        OfferGiveTribute,
        AgreeAcceptTribute,
        RefuseAcceptTribute,
        CancelTribute,
        OfferPeace,
        AgreePeace,
        RefusePeace,
        AskTradeDepotLater,
        ExpressAstonishment,
        CommentWeather,
        CommentNature,
        SummarizeTerritory,
        SummarizePatrols,
        SummarizeOpposition,
        DescribeRefugees,
        AccuseTroublemaker,
        AskAdopt,
        AgreeAdopt,
        RefuseAdopt,
        RevokeService,
        InviteService,
        AcceptInviteService,
        RefuseShareInformation,
        RefuseInviteService,
        RefuseRequestService,
        OfferService,
        AcceptPositionService,
        RefusePositionService,
        InvokeNameBanish,
        InvokeNameService,
        GrovelMaster,
        DemandItem,
        GiveServiceReport,
        OfferEncouragement,
        PraiseTaskCompleter
      };
    }
  }
  using enums::talk_choice_type::talk_choice_type;
  template<> struct DFHACK_EXPORT identity_traits<talk_choice_type> {
    static enum_identity identity;
    static enum_identity *get() { return &identity; }
  };
  template<> struct DFHACK_EXPORT enum_traits<talk_choice_type> {
    typedef int32_t base_type;
    typedef talk_choice_type enum_type;
    static const base_type first_item_value = 0;
    static const base_type last_item_value = 168;
    static inline bool is_valid(enum_type value) {
      return (base_type(value) >= first_item_value && base_type(value) <= last_item_value);
    }
    static const enum_type first_item = (enum_type)first_item_value;
    static const enum_type last_item = (enum_type)last_item_value;
    static const char *const key_table[169];
  };
}
#endif
